# Generated by Django 5.0.1 on 2025-01-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Area_side',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_side_name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Eclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Eclass',
                'verbose_name_plural': 'Eclasses',
            },
        ),
        migrations.CreateModel(
            name='GeneralSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsName', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'GeneralSpecialization',
                'verbose_name_plural': 'GeneralSpecializations',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Nationality',
                'verbose_name_plural': 'Nationalities',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spName', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emptype', models.IntegerField(blank=True, choices=[(1, 'Employee'), (2, 'SOP')], null=True)),
                ('jobtype', models.IntegerField(blank=True, choices=[(1, 'خدمة مدنية'), (2, 'تشغيل ذاتي')], null=True)),
                ('identity', models.IntegerField(blank=True, null=True)),
                ('empno', models.BigIntegerField()),
                ('ename', models.CharField(max_length=75)),
                ('telNo', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sex', models.IntegerField(blank=True, choices=[(1, 'ذكر'), (2, 'انثي')], null=True)),
                ('bdate', models.DateField(blank=True, null=True)),
                ('job_id', models.CharField(blank=True, max_length=20, null=True)),
                ('job_owner', models.CharField(blank=True, max_length=75, null=True)),
                ('owner_side', models.CharField(blank=True, max_length=75, null=True)),
                ('actual_work_area', models.CharField(blank=True, max_length=75, null=True)),
                ('actual_work_side', models.CharField(blank=True, max_length=100, null=True)),
                ('adminstrator', models.CharField(blank=True, max_length=90, null=True)),
                ('lastAction_date', models.CharField(blank=True, max_length=20, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=75, null=True)),
                ('hire_date', models.CharField(blank=True, max_length=20, null=True)),
                ('ministry_attachment', models.CharField(blank=True, max_length=20, null=True)),
                ('country_attachement_date', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_status', models.CharField(blank=True, max_length=75, null=True)),
                ('service_type', models.IntegerField(blank=True, null=True)),
                ('area_side_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.area_side')),
                ('eclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eclass', to='hr.eclass')),
                ('last_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.actions')),
                ('general_specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generalspecialization', to='hr.generalspecialization')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.job')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nationality', to='hr.nationality')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialization', to='hr.specialization')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
